-- Rename remaining worksheets to standard naming convention
-- Format: [Topic] – Grade [X] [Subject] Worksheet [N] – Free Printable

UPDATE worksheets SET title = 'Environment – Grade 2 Science Worksheet 1 – Free Printable' WHERE id = '637';
UPDATE worksheets SET title = 'Environment – Grade 2 Science Worksheet 2 – Free Printable' WHERE id = '638';
UPDATE worksheets SET title = 'Environment – Grade 2 Science Worksheet 3 – Free Printable' WHERE id = '639';
UPDATE worksheets SET title = 'Environment – Grade 2 Science Worksheet 4 – Free Printable' WHERE id = '640';
UPDATE worksheets SET title = 'Environment – Grade 2 Science Worksheet 5 – Free Printable' WHERE id = '641';
UPDATE worksheets SET title = 'Environment – Grade 2 Science Worksheet 6 – Free Printable' WHERE id = '642';
UPDATE worksheets SET title = 'Environment – Grade 2 Science Worksheet 7 – Free Printable' WHERE id = '643';
UPDATE worksheets SET title = 'Environment – Grade 2 Science Worksheet 8 – Free Printable' WHERE id = '644';
UPDATE worksheets SET title = 'Environment – Grade 2 Science Worksheet 9 – Free Printable' WHERE id = '645';
UPDATE worksheets SET title = 'Environment – Grade 2 Science Worksheet 10 – Free Printable' WHERE id = '646';
UPDATE worksheets SET title = 'Food & Water – Grade 2 Science Worksheet 1 – Free Printable' WHERE id = '622';
UPDATE worksheets SET title = 'Food & Water – Grade 2 Science Worksheet 2 – Free Printable' WHERE id = '623';
UPDATE worksheets SET title = 'Food & Water – Grade 2 Science Worksheet 3 – Free Printable' WHERE id = '624';
UPDATE worksheets SET title = 'Food & Water – Grade 2 Science Worksheet 4 – Free Printable' WHERE id = '625';
UPDATE worksheets SET title = 'Food & Water – Grade 2 Science Worksheet 5 – Free Printable' WHERE id = '626';
UPDATE worksheets SET title = 'My Body – Grade 2 Science Worksheet 1 – Free Printable' WHERE id = '627';
UPDATE worksheets SET title = 'My Body – Grade 2 Science Worksheet 2 – Free Printable' WHERE id = '628';
UPDATE worksheets SET title = 'My Body – Grade 2 Science Worksheet 3 – Free Printable' WHERE id = '629';
UPDATE worksheets SET title = 'My Body – Grade 2 Science Worksheet 4 – Free Printable' WHERE id = '630';
UPDATE worksheets SET title = 'My Body – Grade 2 Science Worksheet 5 – Free Printable' WHERE id = '631';
UPDATE worksheets SET title = 'Plants & Animals – Grade 2 Science Worksheet 1 – Free Printable' WHERE id = '617';
UPDATE worksheets SET title = 'Plants & Animals – Grade 2 Science Worksheet 2 – Free Printable' WHERE id = '618';
UPDATE worksheets SET title = 'Plants & Animals – Grade 2 Science Worksheet 3 – Free Printable' WHERE id = '619';
UPDATE worksheets SET title = 'Plants & Animals – Grade 2 Science Worksheet 4 – Free Printable' WHERE id = '620';
UPDATE worksheets SET title = 'Plants & Animals – Grade 2 Science Worksheet 5 – Free Printable' WHERE id = '621';
UPDATE worksheets SET title = 'Plants & Animals – Grade 2 Science Worksheet 6 – Free Printable' WHERE id = '632';
UPDATE worksheets SET title = 'Plants & Animals – Grade 2 Science Worksheet 7 – Free Printable' WHERE id = '633';
UPDATE worksheets SET title = 'Plants & Animals – Grade 2 Science Worksheet 8 – Free Printable' WHERE id = '634';
UPDATE worksheets SET title = 'Plants & Animals – Grade 2 Science Worksheet 9 – Free Printable' WHERE id = '635';
UPDATE worksheets SET title = 'Plants & Animals – Grade 2 Science Worksheet 10 – Free Printable' WHERE id = '636';
UPDATE worksheets SET title = 'CS Assignment Packs – Grade 3 Assignments Worksheet 1 – Free Printable' WHERE id = '158';
UPDATE worksheets SET title = 'CS Assignment Packs – Grade 3 Assignments Worksheet 2 – Free Printable' WHERE id = '159';
UPDATE worksheets SET title = 'CS Assignment Packs – Grade 3 Assignments Worksheet 3 – Free Printable' WHERE id = '160';
UPDATE worksheets SET title = 'CS Assignment Packs – Grade 3 Assignments Worksheet 4 – Free Printable' WHERE id = '161';
UPDATE worksheets SET title = 'CS Assignment Packs – Grade 3 Assignments Worksheet 5 – Free Printable' WHERE id = '162';
UPDATE worksheets SET title = 'English Assignment Packs – Grade 3 Assignments Worksheet 1 – Free Printable' WHERE id = '153';
UPDATE worksheets SET title = 'English Assignment Packs – Grade 3 Assignments Worksheet 2 – Free Printable' WHERE id = '154';
UPDATE worksheets SET title = 'English Assignment Packs – Grade 3 Assignments Worksheet 3 – Free Printable' WHERE id = '155';
UPDATE worksheets SET title = 'English Assignment Packs – Grade 3 Assignments Worksheet 4 – Free Printable' WHERE id = '156';
UPDATE worksheets SET title = 'English Assignment Packs – Grade 3 Assignments Worksheet 5 – Free Printable' WHERE id = '157';
UPDATE worksheets SET title = 'EVS Assignment Packs – Grade 3 Assignments Worksheet 1 – Free Printable' WHERE id = '143';
UPDATE worksheets SET title = 'EVS Assignment Packs – Grade 3 Assignments Worksheet 2 – Free Printable' WHERE id = '144';
UPDATE worksheets SET title = 'EVS Assignment Packs – Grade 3 Assignments Worksheet 3 – Free Printable' WHERE id = '145';
UPDATE worksheets SET title = 'EVS Assignment Packs – Grade 3 Assignments Worksheet 4 – Free Printable' WHERE id = '146';
UPDATE worksheets SET title = 'EVS Assignment Packs – Grade 3 Assignments Worksheet 5 – Free Printable' WHERE id = '147';
UPDATE worksheets SET title = 'Math Assignment Packs – Grade 3 Assignments Worksheet 1 – Free Printable' WHERE id = '148';
UPDATE worksheets SET title = 'Math Assignment Packs – Grade 3 Assignments Worksheet 2 – Free Printable' WHERE id = '149';
UPDATE worksheets SET title = 'Math Assignment Packs – Grade 3 Assignments Worksheet 3 – Free Printable' WHERE id = '150';
UPDATE worksheets SET title = 'Math Assignment Packs – Grade 3 Assignments Worksheet 4 – Free Printable' WHERE id = '151';
UPDATE worksheets SET title = 'Math Assignment Packs – Grade 3 Assignments Worksheet 5 – Free Printable' WHERE id = '152';
UPDATE worksheets SET title = 'Computer Basics – Grade 3 Computer Science Worksheet 1 – Free Printable' WHERE id = '163';
UPDATE worksheets SET title = 'Computer Basics – Grade 3 Computer Science Worksheet 2 – Free Printable' WHERE id = '164';
UPDATE worksheets SET title = 'Computer Basics – Grade 3 Computer Science Worksheet 3 – Free Printable' WHERE id = '165';
UPDATE worksheets SET title = 'Computer Basics – Grade 3 Computer Science Worksheet 4 – Free Printable' WHERE id = '166';
UPDATE worksheets SET title = 'Computer Basics – Grade 3 Computer Science Worksheet 5 – Free Printable' WHERE id = '167';
UPDATE worksheets SET title = 'Computer Basics – Grade 3 Computer Science Worksheet 6 – Free Printable' WHERE id = '173';
UPDATE worksheets SET title = 'Computer Basics – Grade 3 Computer Science Worksheet 7 – Free Printable' WHERE id = '174';
UPDATE worksheets SET title = 'Computer Basics – Grade 3 Computer Science Worksheet 8 – Free Printable' WHERE id = '175';
UPDATE worksheets SET title = 'Computer Basics – Grade 3 Computer Science Worksheet 9 – Free Printable' WHERE id = '176';
UPDATE worksheets SET title = 'Computer Basics – Grade 3 Computer Science Worksheet 10 – Free Printable' WHERE id = '177';
UPDATE worksheets SET title = 'Computer Basics – Grade 3 Computer Science Worksheet 11 – Free Printable' WHERE id = '178';
UPDATE worksheets SET title = 'Computer Basics – Grade 3 Computer Science Worksheet 12 – Free Printable' WHERE id = '179';
UPDATE worksheets SET title = 'Computer Basics – Grade 3 Computer Science Worksheet 13 – Free Printable' WHERE id = '180';
UPDATE worksheets SET title = 'Computer Basics – Grade 3 Computer Science Worksheet 14 – Free Printable' WHERE id = '181';
UPDATE worksheets SET title = 'Computer Basics – Grade 3 Computer Science Worksheet 15 – Free Printable' WHERE id = '182';
UPDATE worksheets SET title = 'Computer Basics – Grade 3 Computer Science Worksheet 16 – Free Printable' WHERE id = '183';
UPDATE worksheets SET title = 'Computer Basics – Grade 3 Computer Science Worksheet 17 – Free Printable' WHERE id = '184';
UPDATE worksheets SET title = 'Computer Basics – Grade 3 Computer Science Worksheet 18 – Free Printable' WHERE id = '185';
UPDATE worksheets SET title = 'Computer Basics – Grade 3 Computer Science Worksheet 19 – Free Printable' WHERE id = '186';
UPDATE worksheets SET title = 'Computer Basics – Grade 3 Computer Science Worksheet 20 – Free Printable' WHERE id = '187';
UPDATE worksheets SET title = 'Computer Basics – Grade 3 Computer Science Worksheet 21 – Free Printable' WHERE id = '193';
UPDATE worksheets SET title = 'Computer Basics – Grade 3 Computer Science Worksheet 22 – Free Printable' WHERE id = '194';
UPDATE worksheets SET title = 'Computer Basics – Grade 3 Computer Science Worksheet 23 – Free Printable' WHERE id = '195';
UPDATE worksheets SET title = 'Computer Basics – Grade 3 Computer Science Worksheet 24 – Free Printable' WHERE id = '196';
UPDATE worksheets SET title = 'Computer Basics – Grade 3 Computer Science Worksheet 25 – Free Printable' WHERE id = '197';
UPDATE worksheets SET title = 'Computer Basics – Grade 3 Computer Science Worksheet 26 – Free Printable' WHERE id = '198';
UPDATE worksheets SET title = 'Computer Basics – Grade 3 Computer Science Worksheet 27 – Free Printable' WHERE id = '199';
UPDATE worksheets SET title = 'Computer Basics – Grade 3 Computer Science Worksheet 28 – Free Printable' WHERE id = '200';
UPDATE worksheets SET title = 'Computer Basics – Grade 3 Computer Science Worksheet 29 – Free Printable' WHERE id = '201';
UPDATE worksheets SET title = 'Computer Basics – Grade 3 Computer Science Worksheet 30 – Free Printable' WHERE id = '202';
UPDATE worksheets SET title = 'Digital Safety – Grade 3 Computer Science Worksheet 1 – Free Printable' WHERE id = '168';
UPDATE worksheets SET title = 'Digital Safety – Grade 3 Computer Science Worksheet 2 – Free Printable' WHERE id = '169';
UPDATE worksheets SET title = 'Digital Safety – Grade 3 Computer Science Worksheet 3 – Free Printable' WHERE id = '170';
UPDATE worksheets SET title = 'Digital Safety – Grade 3 Computer Science Worksheet 4 – Free Printable' WHERE id = '171';
UPDATE worksheets SET title = 'Digital Safety – Grade 3 Computer Science Worksheet 5 – Free Printable' WHERE id = '172';
UPDATE worksheets SET title = 'Keyboard & Mouse – Grade 3 Computer Science Worksheet 1 – Free Printable' WHERE id = '188';
UPDATE worksheets SET title = 'Keyboard & Mouse – Grade 3 Computer Science Worksheet 2 – Free Printable' WHERE id = '189';
UPDATE worksheets SET title = 'Keyboard & Mouse – Grade 3 Computer Science Worksheet 3 – Free Printable' WHERE id = '190';
UPDATE worksheets SET title = 'Keyboard & Mouse – Grade 3 Computer Science Worksheet 4 – Free Printable' WHERE id = '191';
UPDATE worksheets SET title = 'Keyboard & Mouse – Grade 3 Computer Science Worksheet 5 – Free Printable' WHERE id = '192';
UPDATE worksheets SET title = 'Grammar – Grade 3 English Worksheet 1 – Free Printable' WHERE id = '263';
UPDATE worksheets SET title = 'Grammar – Grade 3 English Worksheet 2 – Free Printable' WHERE id = '264';
UPDATE worksheets SET title = 'Grammar – Grade 3 English Worksheet 3 – Free Printable' WHERE id = '265';
UPDATE worksheets SET title = 'Grammar – Grade 3 English Worksheet 4 – Free Printable' WHERE id = '266';
UPDATE worksheets SET title = 'Grammar – Grade 3 English Worksheet 5 – Free Printable' WHERE id = '267';
UPDATE worksheets SET title = 'Phonics – Grade 3 English Worksheet 1 – Free Printable' WHERE id = '248';
UPDATE worksheets SET title = 'Phonics – Grade 3 English Worksheet 2 – Free Printable' WHERE id = '249';
UPDATE worksheets SET title = 'Phonics – Grade 3 English Worksheet 3 – Free Printable' WHERE id = '250';
UPDATE worksheets SET title = 'Phonics – Grade 3 English Worksheet 4 – Free Printable' WHERE id = '251';
UPDATE worksheets SET title = 'Phonics – Grade 3 English Worksheet 5 – Free Printable' WHERE id = '252';
UPDATE worksheets SET title = 'Reading – Grade 3 English Worksheet 1 – Free Printable' WHERE id = '238';
UPDATE worksheets SET title = 'Reading – Grade 3 English Worksheet 2 – Free Printable' WHERE id = '239';
UPDATE worksheets SET title = 'Reading – Grade 3 English Worksheet 3 – Free Printable' WHERE id = '240';
UPDATE worksheets SET title = 'Reading – Grade 3 English Worksheet 4 – Free Printable' WHERE id = '241';
UPDATE worksheets SET title = 'Reading – Grade 3 English Worksheet 5 – Free Printable' WHERE id = '242';
UPDATE worksheets SET title = 'Vocabulary – Grade 3 English Worksheet 1 – Free Printable' WHERE id = '243';
UPDATE worksheets SET title = 'Vocabulary – Grade 3 English Worksheet 2 – Free Printable' WHERE id = '244';
UPDATE worksheets SET title = 'Vocabulary – Grade 3 English Worksheet 3 – Free Printable' WHERE id = '245';
UPDATE worksheets SET title = 'Vocabulary – Grade 3 English Worksheet 4 – Free Printable' WHERE id = '246';
UPDATE worksheets SET title = 'Vocabulary – Grade 3 English Worksheet 5 – Free Printable' WHERE id = '247';
UPDATE worksheets SET title = 'Vocabulary – Grade 3 English Worksheet 6 – Free Printable' WHERE id = '253';
UPDATE worksheets SET title = 'Vocabulary – Grade 3 English Worksheet 7 – Free Printable' WHERE id = '254';
UPDATE worksheets SET title = 'Vocabulary – Grade 3 English Worksheet 8 – Free Printable' WHERE id = '255';
UPDATE worksheets SET title = 'Vocabulary – Grade 3 English Worksheet 9 – Free Printable' WHERE id = '256';
UPDATE worksheets SET title = 'Vocabulary – Grade 3 English Worksheet 10 – Free Printable' WHERE id = '257';
UPDATE worksheets SET title = 'Writing – Grade 3 English Worksheet 1 – Free Printable' WHERE id = '258';
UPDATE worksheets SET title = 'Writing – Grade 3 English Worksheet 2 – Free Printable' WHERE id = '259';
UPDATE worksheets SET title = 'Writing – Grade 3 English Worksheet 3 – Free Printable' WHERE id = '260';
UPDATE worksheets SET title = 'Writing – Grade 3 English Worksheet 4 – Free Printable' WHERE id = '261';
UPDATE worksheets SET title = 'Writing – Grade 3 English Worksheet 5 – Free Printable' WHERE id = '262';
UPDATE worksheets SET title = 'Addition – Grade 3 Math Worksheet 1 – Free Printable' WHERE id = '308';
UPDATE worksheets SET title = 'Addition – Grade 3 Math Worksheet 2 – Free Printable' WHERE id = '309';
UPDATE worksheets SET title = 'Addition – Grade 3 Math Worksheet 3 – Free Printable' WHERE id = '310';
UPDATE worksheets SET title = 'Addition – Grade 3 Math Worksheet 4 – Free Printable' WHERE id = '311';
UPDATE worksheets SET title = 'Addition – Grade 3 Math Worksheet 5 – Free Printable' WHERE id = '312';
UPDATE worksheets SET title = 'Division – Grade 3 Math Worksheet 1 – Free Printable' WHERE id = '283';
UPDATE worksheets SET title = 'Division – Grade 3 Math Worksheet 2 – Free Printable' WHERE id = '284';
UPDATE worksheets SET title = 'Division – Grade 3 Math Worksheet 3 – Free Printable' WHERE id = '285';
UPDATE worksheets SET title = 'Division – Grade 3 Math Worksheet 4 – Free Printable' WHERE id = '286';
UPDATE worksheets SET title = 'Division – Grade 3 Math Worksheet 5 – Free Printable' WHERE id = '287';
UPDATE worksheets SET title = 'Fractions – Grade 3 Math Worksheet 1 – Free Printable' WHERE id = '303';
UPDATE worksheets SET title = 'Fractions – Grade 3 Math Worksheet 2 – Free Printable' WHERE id = '304';
UPDATE worksheets SET title = 'Fractions – Grade 3 Math Worksheet 3 – Free Printable' WHERE id = '305';
UPDATE worksheets SET title = 'Fractions – Grade 3 Math Worksheet 4 – Free Printable' WHERE id = '306';
UPDATE worksheets SET title = 'Fractions – Grade 3 Math Worksheet 5 – Free Printable' WHERE id = '307';
UPDATE worksheets SET title = 'Measurement – Grade 3 Math Worksheet 1 – Free Printable' WHERE id = '298';
UPDATE worksheets SET title = 'Measurement – Grade 3 Math Worksheet 2 – Free Printable' WHERE id = '299';
UPDATE worksheets SET title = 'Measurement – Grade 3 Math Worksheet 3 – Free Printable' WHERE id = '300';
UPDATE worksheets SET title = 'Measurement – Grade 3 Math Worksheet 4 – Free Printable' WHERE id = '301';
UPDATE worksheets SET title = 'Measurement – Grade 3 Math Worksheet 5 – Free Printable' WHERE id = '302';
UPDATE worksheets SET title = 'Multiplication – Grade 3 Math Worksheet 1 – Free Printable' WHERE id = '273';
UPDATE worksheets SET title = 'Multiplication – Grade 3 Math Worksheet 2 – Free Printable' WHERE id = '274';
UPDATE worksheets SET title = 'Multiplication – Grade 3 Math Worksheet 3 – Free Printable' WHERE id = '275';
UPDATE worksheets SET title = 'Multiplication – Grade 3 Math Worksheet 4 – Free Printable' WHERE id = '276';
UPDATE worksheets SET title = 'Multiplication – Grade 3 Math Worksheet 5 – Free Printable' WHERE id = '277';
UPDATE worksheets SET title = 'Numbers – Grade 3 Math Worksheet 1 – Free Printable' WHERE id = '278';
UPDATE worksheets SET title = 'Numbers – Grade 3 Math Worksheet 2 – Free Printable' WHERE id = '279';
UPDATE worksheets SET title = 'Numbers – Grade 3 Math Worksheet 3 – Free Printable' WHERE id = '280';
UPDATE worksheets SET title = 'Numbers – Grade 3 Math Worksheet 4 – Free Printable' WHERE id = '281';
UPDATE worksheets SET title = 'Numbers – Grade 3 Math Worksheet 5 – Free Printable' WHERE id = '282';
UPDATE worksheets SET title = 'Place Value – Grade 3 Math Worksheet 1 – Free Printable' WHERE id = '313';
UPDATE worksheets SET title = 'Place Value – Grade 3 Math Worksheet 2 – Free Printable' WHERE id = '314';
UPDATE worksheets SET title = 'Place Value – Grade 3 Math Worksheet 3 – Free Printable' WHERE id = '315';
UPDATE worksheets SET title = 'Place Value – Grade 3 Math Worksheet 4 – Free Printable' WHERE id = '316';
UPDATE worksheets SET title = 'Place Value – Grade 3 Math Worksheet 5 – Free Printable' WHERE id = '317';
UPDATE worksheets SET title = 'Shapes – Grade 3 Math Worksheet 1 – Free Printable' WHERE id = '293';
UPDATE worksheets SET title = 'Shapes – Grade 3 Math Worksheet 2 – Free Printable' WHERE id = '294';
UPDATE worksheets SET title = 'Shapes – Grade 3 Math Worksheet 3 – Free Printable' WHERE id = '295';
UPDATE worksheets SET title = 'Shapes – Grade 3 Math Worksheet 4 – Free Printable' WHERE id = '296';
UPDATE worksheets SET title = 'Shapes – Grade 3 Math Worksheet 5 – Free Printable' WHERE id = '297';
UPDATE worksheets SET title = 'Subtraction – Grade 3 Math Worksheet 1 – Free Printable' WHERE id = '288';
UPDATE worksheets SET title = 'Subtraction – Grade 3 Math Worksheet 2 – Free Printable' WHERE id = '289';
UPDATE worksheets SET title = 'Subtraction – Grade 3 Math Worksheet 3 – Free Printable' WHERE id = '290';
UPDATE worksheets SET title = 'Subtraction – Grade 3 Math Worksheet 4 – Free Printable' WHERE id = '291';
UPDATE worksheets SET title = 'Subtraction – Grade 3 Math Worksheet 5 – Free Printable' WHERE id = '292';
UPDATE worksheets SET title = 'Time – Grade 3 Math Worksheet 1 – Free Printable' WHERE id = '268';
UPDATE worksheets SET title = 'Time – Grade 3 Math Worksheet 2 – Free Printable' WHERE id = '269';
UPDATE worksheets SET title = 'Time – Grade 3 Math Worksheet 3 – Free Printable' WHERE id = '270';
UPDATE worksheets SET title = 'Time – Grade 3 Math Worksheet 4 – Free Printable' WHERE id = '271';
UPDATE worksheets SET title = 'Time – Grade 3 Math Worksheet 5 – Free Printable' WHERE id = '272';
UPDATE worksheets SET title = 'Environment – Grade 3 Science Worksheet 1 – Free Printable' WHERE id = '208';
UPDATE worksheets SET title = 'Environment – Grade 3 Science Worksheet 2 – Free Printable' WHERE id = '209';
UPDATE worksheets SET title = 'Environment – Grade 3 Science Worksheet 3 – Free Printable' WHERE id = '210';
UPDATE worksheets SET title = 'Environment – Grade 3 Science Worksheet 4 – Free Printable' WHERE id = '211';
UPDATE worksheets SET title = 'Environment – Grade 3 Science Worksheet 5 – Free Printable' WHERE id = '212';
UPDATE worksheets SET title = 'Environment – Grade 3 Science Worksheet 6 – Free Printable' WHERE id = '233';
UPDATE worksheets SET title = 'Environment – Grade 3 Science Worksheet 7 – Free Printable' WHERE id = '234';
UPDATE worksheets SET title = 'Environment – Grade 3 Science Worksheet 8 – Free Printable' WHERE id = '235';
UPDATE worksheets SET title = 'Environment – Grade 3 Science Worksheet 9 – Free Printable' WHERE id = '236';
UPDATE worksheets SET title = 'Environment – Grade 3 Science Worksheet 10 – Free Printable' WHERE id = '237';
UPDATE worksheets SET title = 'Family & Home – Grade 3 Science Worksheet 1 – Free Printable' WHERE id = '228';
UPDATE worksheets SET title = 'Family & Home – Grade 3 Science Worksheet 2 – Free Printable' WHERE id = '229';
UPDATE worksheets SET title = 'Family & Home – Grade 3 Science Worksheet 3 – Free Printable' WHERE id = '230';
UPDATE worksheets SET title = 'Family & Home – Grade 3 Science Worksheet 4 – Free Printable' WHERE id = '231';
UPDATE worksheets SET title = 'Family & Home – Grade 3 Science Worksheet 5 – Free Printable' WHERE id = '232';
UPDATE worksheets SET title = 'Food & Water – Grade 3 Science Worksheet 1 – Free Printable' WHERE id = '218';
UPDATE worksheets SET title = 'Food & Water – Grade 3 Science Worksheet 2 – Free Printable' WHERE id = '219';
UPDATE worksheets SET title = 'Food & Water – Grade 3 Science Worksheet 3 – Free Printable' WHERE id = '220';
UPDATE worksheets SET title = 'Food & Water – Grade 3 Science Worksheet 4 – Free Printable' WHERE id = '221';
UPDATE worksheets SET title = 'Food & Water – Grade 3 Science Worksheet 5 – Free Printable' WHERE id = '222';
UPDATE worksheets SET title = 'My Body – Grade 3 Science Worksheet 1 – Free Printable' WHERE id = '213';
UPDATE worksheets SET title = 'My Body – Grade 3 Science Worksheet 2 – Free Printable' WHERE id = '214';
UPDATE worksheets SET title = 'My Body – Grade 3 Science Worksheet 3 – Free Printable' WHERE id = '215';
UPDATE worksheets SET title = 'My Body – Grade 3 Science Worksheet 4 – Free Printable' WHERE id = '216';
UPDATE worksheets SET title = 'My Body – Grade 3 Science Worksheet 5 – Free Printable' WHERE id = '217';
UPDATE worksheets SET title = 'Plants & Animals – Grade 3 Science Worksheet 1 – Free Printable' WHERE id = '203';
UPDATE worksheets SET title = 'Plants & Animals – Grade 3 Science Worksheet 2 – Free Printable' WHERE id = '204';
UPDATE worksheets SET title = 'Plants & Animals – Grade 3 Science Worksheet 3 – Free Printable' WHERE id = '205';
UPDATE worksheets SET title = 'Plants & Animals – Grade 3 Science Worksheet 4 – Free Printable' WHERE id = '206';
UPDATE worksheets SET title = 'Plants & Animals – Grade 3 Science Worksheet 5 – Free Printable' WHERE id = '207';
UPDATE worksheets SET title = 'Plants & Animals – Grade 3 Science Worksheet 6 – Free Printable' WHERE id = '223';
UPDATE worksheets SET title = 'Plants & Animals – Grade 3 Science Worksheet 7 – Free Printable' WHERE id = '224';
UPDATE worksheets SET title = 'Plants & Animals – Grade 3 Science Worksheet 8 – Free Printable' WHERE id = '225';
UPDATE worksheets SET title = 'Plants & Animals – Grade 3 Science Worksheet 9 – Free Printable' WHERE id = '226';
UPDATE worksheets SET title = 'Plants & Animals – Grade 3 Science Worksheet 10 – Free Printable' WHERE id = '227';
UPDATE worksheets SET title = 'EVS Assignment Packs – Grade 4 Assignments Worksheet 1 – Free Printable' WHERE id = '458';
UPDATE worksheets SET title = 'EVS Assignment Packs – Grade 4 Assignments Worksheet 2 – Free Printable' WHERE id = '459';
UPDATE worksheets SET title = 'EVS Assignment Packs – Grade 4 Assignments Worksheet 3 – Free Printable' WHERE id = '460';
UPDATE worksheets SET title = 'EVS Assignment Packs – Grade 4 Assignments Worksheet 4 – Free Printable' WHERE id = '461';
UPDATE worksheets SET title = 'EVS Assignment Packs – Grade 4 Assignments Worksheet 5 – Free Printable' WHERE id = '462';
UPDATE worksheets SET title = 'Math Assignment Packs – Grade 4 Assignments Worksheet 1 – Free Printable' WHERE id = '463';
UPDATE worksheets SET title = 'Math Assignment Packs – Grade 4 Assignments Worksheet 2 – Free Printable' WHERE id = '464';
UPDATE worksheets SET title = 'Math Assignment Packs – Grade 4 Assignments Worksheet 3 – Free Printable' WHERE id = '465';
UPDATE worksheets SET title = 'Math Assignment Packs – Grade 4 Assignments Worksheet 4 – Free Printable' WHERE id = '466';
UPDATE worksheets SET title = 'Math Assignment Packs – Grade 4 Assignments Worksheet 5 – Free Printable' WHERE id = '467';
UPDATE worksheets SET title = 'Computer Basics – Grade 4 Computer Science Worksheet 1 – Free Printable' WHERE id = '468';
UPDATE worksheets SET title = 'Computer Basics – Grade 4 Computer Science Worksheet 2 – Free Printable' WHERE id = '469';
UPDATE worksheets SET title = 'Computer Basics – Grade 4 Computer Science Worksheet 3 – Free Printable' WHERE id = '470';
UPDATE worksheets SET title = 'Computer Basics – Grade 4 Computer Science Worksheet 4 – Free Printable' WHERE id = '471';
UPDATE worksheets SET title = 'Computer Basics – Grade 4 Computer Science Worksheet 5 – Free Printable' WHERE id = '472';
UPDATE worksheets SET title = 'Computer Basics – Grade 4 Computer Science Worksheet 6 – Free Printable' WHERE id = '473';
UPDATE worksheets SET title = 'Computer Basics – Grade 4 Computer Science Worksheet 7 – Free Printable' WHERE id = '474';
UPDATE worksheets SET title = 'Computer Basics – Grade 4 Computer Science Worksheet 8 – Free Printable' WHERE id = '475';
UPDATE worksheets SET title = 'Computer Basics – Grade 4 Computer Science Worksheet 9 – Free Printable' WHERE id = '476';
UPDATE worksheets SET title = 'Computer Basics – Grade 4 Computer Science Worksheet 10 – Free Printable' WHERE id = '477';
UPDATE worksheets SET title = 'Grammar – Grade 4 English Worksheet 1 – Free Printable' WHERE id = '532';
UPDATE worksheets SET title = 'Grammar – Grade 4 English Worksheet 2 – Free Printable' WHERE id = '533';
UPDATE worksheets SET title = 'Grammar – Grade 4 English Worksheet 3 – Free Printable' WHERE id = '534';
UPDATE worksheets SET title = 'Grammar – Grade 4 English Worksheet 4 – Free Printable' WHERE id = '535';
UPDATE worksheets SET title = 'Grammar – Grade 4 English Worksheet 5 – Free Printable' WHERE id = '536';
UPDATE worksheets SET title = 'Phonics – Grade 4 English Worksheet 1 – Free Printable' WHERE id = '542';
UPDATE worksheets SET title = 'Phonics – Grade 4 English Worksheet 2 – Free Printable' WHERE id = '543';
UPDATE worksheets SET title = 'Phonics – Grade 4 English Worksheet 3 – Free Printable' WHERE id = '544';
UPDATE worksheets SET title = 'Phonics – Grade 4 English Worksheet 4 – Free Printable' WHERE id = '545';
UPDATE worksheets SET title = 'Phonics – Grade 4 English Worksheet 5 – Free Printable' WHERE id = '546';
UPDATE worksheets SET title = 'Reading – Grade 4 English Worksheet 1 – Free Printable' WHERE id = '527';
UPDATE worksheets SET title = 'Reading – Grade 4 English Worksheet 2 – Free Printable' WHERE id = '528';
UPDATE worksheets SET title = 'Reading – Grade 4 English Worksheet 3 – Free Printable' WHERE id = '529';
UPDATE worksheets SET title = 'Reading – Grade 4 English Worksheet 4 – Free Printable' WHERE id = '530';
UPDATE worksheets SET title = 'Reading – Grade 4 English Worksheet 5 – Free Printable' WHERE id = '531';
UPDATE worksheets SET title = 'Vocabulary – Grade 4 English Worksheet 1 – Free Printable' WHERE id = '547';
UPDATE worksheets SET title = 'Vocabulary – Grade 4 English Worksheet 2 – Free Printable' WHERE id = '548';
UPDATE worksheets SET title = 'Vocabulary – Grade 4 English Worksheet 3 – Free Printable' WHERE id = '549';
UPDATE worksheets SET title = 'Vocabulary – Grade 4 English Worksheet 4 – Free Printable' WHERE id = '550';
UPDATE worksheets SET title = 'Vocabulary – Grade 4 English Worksheet 5 – Free Printable' WHERE id = '551';
UPDATE worksheets SET title = 'English – Grade 4 Worksheet 1 – Free Printable' WHERE id = '537';
UPDATE worksheets SET title = 'English – Grade 4 Worksheet 2 – Free Printable' WHERE id = '538';
UPDATE worksheets SET title = 'English – Grade 4 Worksheet 3 – Free Printable' WHERE id = '539';
UPDATE worksheets SET title = 'English – Grade 4 Worksheet 4 – Free Printable' WHERE id = '540';
UPDATE worksheets SET title = 'English – Grade 4 Worksheet 5 – Free Printable' WHERE id = '541';
UPDATE worksheets SET title = 'Add Sub WS – Grade 4 Math Worksheet 1 – Free Printable' WHERE id = '562';
UPDATE worksheets SET title = 'Add Sub WS – Grade 4 Math Worksheet 2 – Free Printable' WHERE id = '563';
UPDATE worksheets SET title = 'Add Sub WS – Grade 4 Math Worksheet 3 – Free Printable' WHERE id = '564';
UPDATE worksheets SET title = 'Add Sub WS – Grade 4 Math Worksheet 4 – Free Printable' WHERE id = '565';
UPDATE worksheets SET title = 'Add Sub WS – Grade 4 Math Worksheet 5 – Free Printable' WHERE id = '566';
UPDATE worksheets SET title = 'Division WS – Grade 4 Math Worksheet 1 – Free Printable' WHERE id = '582';
UPDATE worksheets SET title = 'Division WS – Grade 4 Math Worksheet 2 – Free Printable' WHERE id = '583';
UPDATE worksheets SET title = 'Division WS – Grade 4 Math Worksheet 3 – Free Printable' WHERE id = '584';
UPDATE worksheets SET title = 'Division WS – Grade 4 Math Worksheet 4 – Free Printable' WHERE id = '585';
UPDATE worksheets SET title = 'Division WS – Grade 4 Math Worksheet 5 – Free Printable' WHERE id = '586';
UPDATE worksheets SET title = 'Fractions WS – Grade 4 Math Worksheet 1 – Free Printable' WHERE id = '587';
UPDATE worksheets SET title = 'Fractions WS – Grade 4 Math Worksheet 2 – Free Printable' WHERE id = '588';
UPDATE worksheets SET title = 'Fractions WS – Grade 4 Math Worksheet 3 – Free Printable' WHERE id = '589';
UPDATE worksheets SET title = 'Fractions WS – Grade 4 Math Worksheet 4 – Free Printable' WHERE id = '590';
UPDATE worksheets SET title = 'Fractions WS – Grade 4 Math Worksheet 5 – Free Printable' WHERE id = '591';
UPDATE worksheets SET title = 'Measurement WS – Grade 4 Math Worksheet 1 – Free Printable' WHERE id = '557';
UPDATE worksheets SET title = 'Measurement WS – Grade 4 Math Worksheet 2 – Free Printable' WHERE id = '558';
UPDATE worksheets SET title = 'Measurement WS – Grade 4 Math Worksheet 3 – Free Printable' WHERE id = '559';
UPDATE worksheets SET title = 'Measurement WS – Grade 4 Math Worksheet 4 – Free Printable' WHERE id = '560';
UPDATE worksheets SET title = 'Measurement WS – Grade 4 Math Worksheet 5 – Free Printable' WHERE id = '561';
UPDATE worksheets SET title = 'Multiplication WS – Grade 4 Math Worksheet 1 – Free Printable' WHERE id = '567';
UPDATE worksheets SET title = 'Multiplication WS – Grade 4 Math Worksheet 2 – Free Printable' WHERE id = '568';
UPDATE worksheets SET title = 'Multiplication WS – Grade 4 Math Worksheet 3 – Free Printable' WHERE id = '569';
UPDATE worksheets SET title = 'Multiplication WS – Grade 4 Math Worksheet 4 – Free Printable' WHERE id = '570';
UPDATE worksheets SET title = 'Multiplication WS – Grade 4 Math Worksheet 5 – Free Printable' WHERE id = '571';
UPDATE worksheets SET title = 'Place Value – Grade 4 Math Worksheet 1 – Free Printable' WHERE id = '552';
UPDATE worksheets SET title = 'Place Value – Grade 4 Math Worksheet 2 – Free Printable' WHERE id = '553';
UPDATE worksheets SET title = 'Place Value – Grade 4 Math Worksheet 3 – Free Printable' WHERE id = '554';
UPDATE worksheets SET title = 'Place Value – Grade 4 Math Worksheet 4 – Free Printable' WHERE id = '555';
UPDATE worksheets SET title = 'Place Value – Grade 4 Math Worksheet 5 – Free Printable' WHERE id = '556';
UPDATE worksheets SET title = 'Shapes – Grade 4 Math Worksheet 1 – Free Printable' WHERE id = '577';
UPDATE worksheets SET title = 'Shapes – Grade 4 Math Worksheet 2 – Free Printable' WHERE id = '578';
UPDATE worksheets SET title = 'Shapes – Grade 4 Math Worksheet 3 – Free Printable' WHERE id = '579';
UPDATE worksheets SET title = 'Shapes – Grade 4 Math Worksheet 4 – Free Printable' WHERE id = '580';
UPDATE worksheets SET title = 'Shapes – Grade 4 Math Worksheet 5 – Free Printable' WHERE id = '581';
UPDATE worksheets SET title = 'Time WS – Grade 4 Math Worksheet 1 – Free Printable' WHERE id = '572';
UPDATE worksheets SET title = 'Time WS – Grade 4 Math Worksheet 2 – Free Printable' WHERE id = '573';
UPDATE worksheets SET title = 'Time WS – Grade 4 Math Worksheet 3 – Free Printable' WHERE id = '574';
UPDATE worksheets SET title = 'Time WS – Grade 4 Math Worksheet 4 – Free Printable' WHERE id = '575';
UPDATE worksheets SET title = 'Time WS – Grade 4 Math Worksheet 5 – Free Printable' WHERE id = '576';
UPDATE worksheets SET title = 'Environment – Grade 4 Science Worksheet 1 – Free Printable' WHERE id = '507';
UPDATE worksheets SET title = 'Environment – Grade 4 Science Worksheet 2 – Free Printable' WHERE id = '508';
UPDATE worksheets SET title = 'Environment – Grade 4 Science Worksheet 3 – Free Printable' WHERE id = '509';
UPDATE worksheets SET title = 'Environment – Grade 4 Science Worksheet 4 – Free Printable' WHERE id = '510';
UPDATE worksheets SET title = 'Environment – Grade 4 Science Worksheet 5 – Free Printable' WHERE id = '511';
UPDATE worksheets SET title = 'Food & Water – Grade 4 Science Worksheet 1 – Free Printable' WHERE id = '483';
UPDATE worksheets SET title = 'Food & Water – Grade 4 Science Worksheet 2 – Free Printable' WHERE id = '484';
UPDATE worksheets SET title = 'Food & Water – Grade 4 Science Worksheet 3 – Free Printable' WHERE id = '485';
UPDATE worksheets SET title = 'Food & Water – Grade 4 Science Worksheet 4 – Free Printable' WHERE id = '486';
UPDATE worksheets SET title = 'Food & Water – Grade 4 Science Worksheet 5 – Free Printable' WHERE id = '487';
UPDATE worksheets SET title = 'Food & Water – Grade 4 Science Worksheet 6 – Free Printable' WHERE id = '512';
UPDATE worksheets SET title = 'Food & Water – Grade 4 Science Worksheet 7 – Free Printable' WHERE id = '513';
UPDATE worksheets SET title = 'Food & Water – Grade 4 Science Worksheet 8 – Free Printable' WHERE id = '514';
UPDATE worksheets SET title = 'Food & Water – Grade 4 Science Worksheet 9 – Free Printable' WHERE id = '515';
UPDATE worksheets SET title = 'Food & Water – Grade 4 Science Worksheet 10 – Free Printable' WHERE id = '516';
UPDATE worksheets SET title = 'Force & Energy – Grade 4 Science Worksheet 1 – Free Printable' WHERE id = '502';
UPDATE worksheets SET title = 'Force & Energy – Grade 4 Science Worksheet 2 – Free Printable' WHERE id = '503';
UPDATE worksheets SET title = 'Force & Energy – Grade 4 Science Worksheet 3 – Free Printable' WHERE id = '504';
UPDATE worksheets SET title = 'Force & Energy – Grade 4 Science Worksheet 4 – Free Printable' WHERE id = '505';
UPDATE worksheets SET title = 'Force & Energy – Grade 4 Science Worksheet 5 – Free Printable' WHERE id = '506';
UPDATE worksheets SET title = 'Light & Shadow – Grade 4 Science Worksheet 1 – Free Printable' WHERE id = '488';
UPDATE worksheets SET title = 'Light & Shadow – Grade 4 Science Worksheet 2 – Free Printable' WHERE id = '489';
UPDATE worksheets SET title = 'Light & Shadow – Grade 4 Science Worksheet 3 – Free Printable' WHERE id = '490';
UPDATE worksheets SET title = 'Light & Shadow – Grade 4 Science Worksheet 4 – Free Printable' WHERE id = '491';
UPDATE worksheets SET title = 'Light & Shadow – Grade 4 Science Worksheet 5 – Free Printable' WHERE id = '492';
UPDATE worksheets SET title = 'Plants & Animals – Grade 4 Science Worksheet 1 – Free Printable' WHERE id = '493';
UPDATE worksheets SET title = 'Plants & Animals – Grade 4 Science Worksheet 2 – Free Printable' WHERE id = '494';
UPDATE worksheets SET title = 'Plants & Animals – Grade 4 Science Worksheet 3 – Free Printable' WHERE id = '495';
UPDATE worksheets SET title = 'Plants & Animals – Grade 4 Science Worksheet 4 – Free Printable' WHERE id = '496';
UPDATE worksheets SET title = 'Plants & Animals – Grade 4 Science Worksheet 5 – Free Printable' WHERE id = '517';
UPDATE worksheets SET title = 'Plants & Animals – Grade 4 Science Worksheet 6 – Free Printable' WHERE id = '518';
UPDATE worksheets SET title = 'Plants & Animals – Grade 4 Science Worksheet 7 – Free Printable' WHERE id = '519';
UPDATE worksheets SET title = 'Plants & Animals – Grade 4 Science Worksheet 8 – Free Printable' WHERE id = '520';
UPDATE worksheets SET title = 'Plants & Animals – Grade 4 Science Worksheet 9 – Free Printable' WHERE id = '521';
UPDATE worksheets SET title = 'Safety & First Aid – Grade 4 Science Worksheet 1 – Free Printable' WHERE id = '497';
UPDATE worksheets SET title = 'Safety & First Aid – Grade 4 Science Worksheet 2 – Free Printable' WHERE id = '498';
UPDATE worksheets SET title = 'Safety & First Aid – Grade 4 Science Worksheet 3 – Free Printable' WHERE id = '499';
UPDATE worksheets SET title = 'Safety & First Aid – Grade 4 Science Worksheet 4 – Free Printable' WHERE id = '500';
UPDATE worksheets SET title = 'Safety & First Aid – Grade 4 Science Worksheet 5 – Free Printable' WHERE id = '501';
UPDATE worksheets SET title = 'States of Matter – Grade 4 Science Worksheet 1 – Free Printable' WHERE id = '522';
UPDATE worksheets SET title = 'States of Matter – Grade 4 Science Worksheet 2 – Free Printable' WHERE id = '523';
UPDATE worksheets SET title = 'States of Matter – Grade 4 Science Worksheet 3 – Free Printable' WHERE id = '524';
UPDATE worksheets SET title = 'States of Matter – Grade 4 Science Worksheet 4 – Free Printable' WHERE id = '525';
UPDATE worksheets SET title = 'States of Matter – Grade 4 Science Worksheet 5 – Free Printable' WHERE id = '526';
UPDATE worksheets SET title = 'Teeth & Microbes – Grade 4 Science Worksheet 1 – Free Printable' WHERE id = '478';
UPDATE worksheets SET title = 'Teeth & Microbes – Grade 4 Science Worksheet 2 – Free Printable' WHERE id = '479';
UPDATE worksheets SET title = 'Teeth & Microbes – Grade 4 Science Worksheet 3 – Free Printable' WHERE id = '480';
UPDATE worksheets SET title = 'Teeth & Microbes – Grade 4 Science Worksheet 4 – Free Printable' WHERE id = '481';
UPDATE worksheets SET title = 'Teeth & Microbes – Grade 4 Science Worksheet 5 – Free Printable' WHERE id = '482';
UPDATE worksheets SET title = 'Computer Basics – Grade 5 Computer Science Worksheet 1 – Free Printable' WHERE id = '323';
UPDATE worksheets SET title = 'Computer Basics – Grade 5 Computer Science Worksheet 2 – Free Printable' WHERE id = '324';
UPDATE worksheets SET title = 'Computer Basics – Grade 5 Computer Science Worksheet 3 – Free Printable' WHERE id = '325';
UPDATE worksheets SET title = 'Computer Basics – Grade 5 Computer Science Worksheet 4 – Free Printable' WHERE id = '326';
UPDATE worksheets SET title = 'Computer Basics – Grade 5 Computer Science Worksheet 5 – Free Printable' WHERE id = '327';
UPDATE worksheets SET title = 'Computer Basics – Grade 5 Computer Science Worksheet 6 – Free Printable' WHERE id = '328';
UPDATE worksheets SET title = 'Computer Basics – Grade 5 Computer Science Worksheet 7 – Free Printable' WHERE id = '329';
UPDATE worksheets SET title = 'Computer Basics – Grade 5 Computer Science Worksheet 8 – Free Printable' WHERE id = '330';
UPDATE worksheets SET title = 'Computer Basics – Grade 5 Computer Science Worksheet 9 – Free Printable' WHERE id = '331';
UPDATE worksheets SET title = 'Computer Basics – Grade 5 Computer Science Worksheet 10 – Free Printable' WHERE id = '332';
UPDATE worksheets SET title = 'Computer Basics – Grade 5 Computer Science Worksheet 11 – Free Printable' WHERE id = '333';
UPDATE worksheets SET title = 'Computer Basics – Grade 5 Computer Science Worksheet 12 – Free Printable' WHERE id = '334';
UPDATE worksheets SET title = 'Computer Basics – Grade 5 Computer Science Worksheet 13 – Free Printable' WHERE id = '335';
UPDATE worksheets SET title = 'Computer Basics – Grade 5 Computer Science Worksheet 14 – Free Printable' WHERE id = '336';
UPDATE worksheets SET title = 'Computer Basics – Grade 5 Computer Science Worksheet 15 – Free Printable' WHERE id = '337';
UPDATE worksheets SET title = 'Digital Safety – Grade 5 Computer Science Worksheet 1 – Free Printable' WHERE id = '318';
UPDATE worksheets SET title = 'Digital Safety – Grade 5 Computer Science Worksheet 2 – Free Printable' WHERE id = '319';
UPDATE worksheets SET title = 'Digital Safety – Grade 5 Computer Science Worksheet 3 – Free Printable' WHERE id = '320';
UPDATE worksheets SET title = 'Digital Safety – Grade 5 Computer Science Worksheet 4 – Free Printable' WHERE id = '321';
UPDATE worksheets SET title = 'Digital Safety – Grade 5 Computer Science Worksheet 5 – Free Printable' WHERE id = '322';
UPDATE worksheets SET title = 'Grammar – Grade 5 English Worksheet 1 – Free Printable' WHERE id = '398';
UPDATE worksheets SET title = 'Grammar – Grade 5 English Worksheet 2 – Free Printable' WHERE id = '399';
UPDATE worksheets SET title = 'Grammar – Grade 5 English Worksheet 3 – Free Printable' WHERE id = '400';
UPDATE worksheets SET title = 'Grammar – Grade 5 English Worksheet 4 – Free Printable' WHERE id = '401';
UPDATE worksheets SET title = 'Grammar – Grade 5 English Worksheet 5 – Free Printable' WHERE id = '402';
UPDATE worksheets SET title = 'Phonics – Grade 5 English Worksheet 1 – Free Printable' WHERE id = '408';
UPDATE worksheets SET title = 'Phonics – Grade 5 English Worksheet 2 – Free Printable' WHERE id = '409';
UPDATE worksheets SET title = 'Phonics – Grade 5 English Worksheet 3 – Free Printable' WHERE id = '410';
UPDATE worksheets SET title = 'Phonics – Grade 5 English Worksheet 4 – Free Printable' WHERE id = '411';
UPDATE worksheets SET title = 'Phonics – Grade 5 English Worksheet 5 – Free Printable' WHERE id = '412';
UPDATE worksheets SET title = 'Reading – Grade 5 English Worksheet 1 – Free Printable' WHERE id = '393';
UPDATE worksheets SET title = 'Reading – Grade 5 English Worksheet 2 – Free Printable' WHERE id = '394';
UPDATE worksheets SET title = 'Reading – Grade 5 English Worksheet 3 – Free Printable' WHERE id = '395';
UPDATE worksheets SET title = 'Reading – Grade 5 English Worksheet 4 – Free Printable' WHERE id = '396';
UPDATE worksheets SET title = 'Reading – Grade 5 English Worksheet 5 – Free Printable' WHERE id = '397';
UPDATE worksheets SET title = 'Vocabulary – Grade 5 English Worksheet 1 – Free Printable' WHERE id = '403';
UPDATE worksheets SET title = 'Vocabulary – Grade 5 English Worksheet 2 – Free Printable' WHERE id = '404';
UPDATE worksheets SET title = 'Vocabulary – Grade 5 English Worksheet 3 – Free Printable' WHERE id = '405';
UPDATE worksheets SET title = 'Vocabulary – Grade 5 English Worksheet 4 – Free Printable' WHERE id = '406';
UPDATE worksheets SET title = 'Vocabulary – Grade 5 English Worksheet 5 – Free Printable' WHERE id = '407';
UPDATE worksheets SET title = 'Writing – Grade 5 English Worksheet 1 – Free Printable' WHERE id = '413';
UPDATE worksheets SET title = 'Writing – Grade 5 English Worksheet 2 – Free Printable' WHERE id = '414';
UPDATE worksheets SET title = 'Writing – Grade 5 English Worksheet 3 – Free Printable' WHERE id = '415';
UPDATE worksheets SET title = 'Writing – Grade 5 English Worksheet 4 – Free Printable' WHERE id = '416';
UPDATE worksheets SET title = 'Writing – Grade 5 English Worksheet 5 – Free Printable' WHERE id = '417';
UPDATE worksheets SET title = 'Decimals WS – Grade 5 Math Worksheet 1 – Free Printable' WHERE id = '443';
UPDATE worksheets SET title = 'Decimals WS – Grade 5 Math Worksheet 2 – Free Printable' WHERE id = '444';
UPDATE worksheets SET title = 'Decimals WS – Grade 5 Math Worksheet 3 – Free Printable' WHERE id = '445';
UPDATE worksheets SET title = 'Decimals WS – Grade 5 Math Worksheet 4 – Free Printable' WHERE id = '446';
UPDATE worksheets SET title = 'Decimals WS – Grade 5 Math Worksheet 5 – Free Printable' WHERE id = '447';
UPDATE worksheets SET title = 'Fractions WS – Grade 5 Math Worksheet 1 – Free Printable' WHERE id = '448';
UPDATE worksheets SET title = 'Fractions WS – Grade 5 Math Worksheet 2 – Free Printable' WHERE id = '449';
UPDATE worksheets SET title = 'Fractions WS – Grade 5 Math Worksheet 3 – Free Printable' WHERE id = '450';
UPDATE worksheets SET title = 'Fractions WS – Grade 5 Math Worksheet 4 – Free Printable' WHERE id = '451';
UPDATE worksheets SET title = 'Fractions WS – Grade 5 Math Worksheet 5 – Free Printable' WHERE id = '452';
UPDATE worksheets SET title = 'Geometry WS – Grade 5 Math Worksheet 1 – Free Printable' WHERE id = '433';
UPDATE worksheets SET title = 'Geometry WS – Grade 5 Math Worksheet 2 – Free Printable' WHERE id = '434';
UPDATE worksheets SET title = 'Geometry WS – Grade 5 Math Worksheet 3 – Free Printable' WHERE id = '435';
UPDATE worksheets SET title = 'Geometry WS – Grade 5 Math Worksheet 4 – Free Printable' WHERE id = '436';
UPDATE worksheets SET title = 'Geometry WS – Grade 5 Math Worksheet 5 – Free Printable' WHERE id = '437';
UPDATE worksheets SET title = 'Measurement WS – Grade 5 Math Worksheet 1 – Free Printable' WHERE id = '438';
UPDATE worksheets SET title = 'Measurement WS – Grade 5 Math Worksheet 2 – Free Printable' WHERE id = '439';
UPDATE worksheets SET title = 'Measurement WS – Grade 5 Math Worksheet 3 – Free Printable' WHERE id = '440';
UPDATE worksheets SET title = 'Measurement WS – Grade 5 Math Worksheet 4 – Free Printable' WHERE id = '441';
UPDATE worksheets SET title = 'Measurement WS – Grade 5 Math Worksheet 5 – Free Printable' WHERE id = '442';
UPDATE worksheets SET title = 'Operations WS – Grade 5 Math Worksheet 1 – Free Printable' WHERE id = '428';
UPDATE worksheets SET title = 'Operations WS – Grade 5 Math Worksheet 2 – Free Printable' WHERE id = '429';
UPDATE worksheets SET title = 'Operations WS – Grade 5 Math Worksheet 3 – Free Printable' WHERE id = '430';
UPDATE worksheets SET title = 'Operations WS – Grade 5 Math Worksheet 4 – Free Printable' WHERE id = '431';
UPDATE worksheets SET title = 'Operations WS – Grade 5 Math Worksheet 5 – Free Printable' WHERE id = '432';
UPDATE worksheets SET title = 'Shapes – Grade 5 Math Worksheet 1 – Free Printable' WHERE id = '453';
UPDATE worksheets SET title = 'Shapes – Grade 5 Math Worksheet 2 – Free Printable' WHERE id = '454';
UPDATE worksheets SET title = 'Shapes – Grade 5 Math Worksheet 3 – Free Printable' WHERE id = '455';
UPDATE worksheets SET title = 'Shapes – Grade 5 Math Worksheet 4 – Free Printable' WHERE id = '456';
UPDATE worksheets SET title = 'Shapes – Grade 5 Math Worksheet 5 – Free Printable' WHERE id = '457';
UPDATE worksheets SET title = 'Time Money WS – Grade 5 Math Worksheet 1 – Free Printable' WHERE id = '423';
UPDATE worksheets SET title = 'Time Money WS – Grade 5 Math Worksheet 2 – Free Printable' WHERE id = '424';
UPDATE worksheets SET title = 'Time Money WS – Grade 5 Math Worksheet 3 – Free Printable' WHERE id = '425';
UPDATE worksheets SET title = 'Time Money WS – Grade 5 Math Worksheet 4 – Free Printable' WHERE id = '426';
UPDATE worksheets SET title = 'Time Money WS – Grade 5 Math Worksheet 5 – Free Printable' WHERE id = '427';
UPDATE worksheets SET title = 'Word Problems – Grade 5 Math Worksheet 1 – Free Printable' WHERE id = '418';
UPDATE worksheets SET title = 'Word Problems – Grade 5 Math Worksheet 2 – Free Printable' WHERE id = '419';
UPDATE worksheets SET title = 'Word Problems – Grade 5 Math Worksheet 3 – Free Printable' WHERE id = '420';
UPDATE worksheets SET title = 'Word Problems – Grade 5 Math Worksheet 4 – Free Printable' WHERE id = '421';
UPDATE worksheets SET title = 'Word Problems – Grade 5 Math Worksheet 5 – Free Printable' WHERE id = '422';
UPDATE worksheets SET title = 'Environment – Grade 5 Science Worksheet 1 – Free Printable' WHERE id = '343';
UPDATE worksheets SET title = 'Environment – Grade 5 Science Worksheet 2 – Free Printable' WHERE id = '344';
UPDATE worksheets SET title = 'Environment – Grade 5 Science Worksheet 3 – Free Printable' WHERE id = '345';
UPDATE worksheets SET title = 'Environment – Grade 5 Science Worksheet 4 – Free Printable' WHERE id = '346';
UPDATE worksheets SET title = 'Environment – Grade 5 Science Worksheet 5 – Free Printable' WHERE id = '347';
UPDATE worksheets SET title = 'Environment – Grade 5 Science Worksheet 6 – Free Printable' WHERE id = '368';
UPDATE worksheets SET title = 'Environment – Grade 5 Science Worksheet 7 – Free Printable' WHERE id = '369';
UPDATE worksheets SET title = 'Environment – Grade 5 Science Worksheet 8 – Free Printable' WHERE id = '370';
UPDATE worksheets SET title = 'Environment – Grade 5 Science Worksheet 9 – Free Printable' WHERE id = '371';
UPDATE worksheets SET title = 'Environment – Grade 5 Science Worksheet 10 – Free Printable' WHERE id = '372';
UPDATE worksheets SET title = 'Food & Water – Grade 5 Science Worksheet 1 – Free Printable' WHERE id = '348';
UPDATE worksheets SET title = 'Food & Water – Grade 5 Science Worksheet 2 – Free Printable' WHERE id = '349';
UPDATE worksheets SET title = 'Food & Water – Grade 5 Science Worksheet 3 – Free Printable' WHERE id = '350';
UPDATE worksheets SET title = 'Food & Water – Grade 5 Science Worksheet 4 – Free Printable' WHERE id = '351';
UPDATE worksheets SET title = 'Food & Water – Grade 5 Science Worksheet 5 – Free Printable' WHERE id = '352';
UPDATE worksheets SET title = 'Food & Water – Grade 5 Science Worksheet 6 – Free Printable' WHERE id = '378';
UPDATE worksheets SET title = 'Food & Water – Grade 5 Science Worksheet 7 – Free Printable' WHERE id = '379';
UPDATE worksheets SET title = 'Food & Water – Grade 5 Science Worksheet 8 – Free Printable' WHERE id = '380';
UPDATE worksheets SET title = 'Food & Water – Grade 5 Science Worksheet 9 – Free Printable' WHERE id = '381';
UPDATE worksheets SET title = 'Food & Water – Grade 5 Science Worksheet 10 – Free Printable' WHERE id = '382';
UPDATE worksheets SET title = 'Force & Energy – Grade 5 Science Worksheet 1 – Free Printable' WHERE id = '363';
UPDATE worksheets SET title = 'Force & Energy – Grade 5 Science Worksheet 2 – Free Printable' WHERE id = '364';
UPDATE worksheets SET title = 'Force & Energy – Grade 5 Science Worksheet 3 – Free Printable' WHERE id = '365';
UPDATE worksheets SET title = 'Force & Energy – Grade 5 Science Worksheet 4 – Free Printable' WHERE id = '366';
UPDATE worksheets SET title = 'Force & Energy – Grade 5 Science Worksheet 5 – Free Printable' WHERE id = '367';
UPDATE worksheets SET title = 'Light & Shadow – Grade 5 Science Worksheet 1 – Free Printable' WHERE id = '358';
UPDATE worksheets SET title = 'Light & Shadow – Grade 5 Science Worksheet 2 – Free Printable' WHERE id = '359';
UPDATE worksheets SET title = 'Light & Shadow – Grade 5 Science Worksheet 3 – Free Printable' WHERE id = '360';
UPDATE worksheets SET title = 'Light & Shadow – Grade 5 Science Worksheet 4 – Free Printable' WHERE id = '361';
UPDATE worksheets SET title = 'Light & Shadow – Grade 5 Science Worksheet 5 – Free Printable' WHERE id = '362';
UPDATE worksheets SET title = 'My Body – Grade 5 Science Worksheet 1 – Free Printable' WHERE id = '383';
UPDATE worksheets SET title = 'My Body – Grade 5 Science Worksheet 2 – Free Printable' WHERE id = '384';
UPDATE worksheets SET title = 'My Body – Grade 5 Science Worksheet 3 – Free Printable' WHERE id = '385';
UPDATE worksheets SET title = 'My Body – Grade 5 Science Worksheet 4 – Free Printable' WHERE id = '386';
UPDATE worksheets SET title = 'My Body – Grade 5 Science Worksheet 5 – Free Printable' WHERE id = '387';
UPDATE worksheets SET title = 'Plants & Animals – Grade 5 Science Worksheet 1 – Free Printable' WHERE id = '373';
UPDATE worksheets SET title = 'Plants & Animals – Grade 5 Science Worksheet 2 – Free Printable' WHERE id = '374';
UPDATE worksheets SET title = 'Plants & Animals – Grade 5 Science Worksheet 3 – Free Printable' WHERE id = '375';
UPDATE worksheets SET title = 'Plants & Animals – Grade 5 Science Worksheet 4 – Free Printable' WHERE id = '376';
UPDATE worksheets SET title = 'Plants & Animals – Grade 5 Science Worksheet 5 – Free Printable' WHERE id = '377';
UPDATE worksheets SET title = 'Plants & Animals – Grade 5 Science Worksheet 6 – Free Printable' WHERE id = '388';
UPDATE worksheets SET title = 'Plants & Animals – Grade 5 Science Worksheet 7 – Free Printable' WHERE id = '389';
UPDATE worksheets SET title = 'Plants & Animals – Grade 5 Science Worksheet 8 – Free Printable' WHERE id = '390';
UPDATE worksheets SET title = 'Plants & Animals – Grade 5 Science Worksheet 9 – Free Printable' WHERE id = '391';
UPDATE worksheets SET title = 'Plants & Animals – Grade 5 Science Worksheet 10 – Free Printable' WHERE id = '392';
UPDATE worksheets SET title = 'Simple Machines – Grade 5 Science Worksheet 1 – Free Printable' WHERE id = '353';
UPDATE worksheets SET title = 'Simple Machines – Grade 5 Science Worksheet 2 – Free Printable' WHERE id = '354';
UPDATE worksheets SET title = 'Simple Machines – Grade 5 Science Worksheet 3 – Free Printable' WHERE id = '355';
UPDATE worksheets SET title = 'Simple Machines – Grade 5 Science Worksheet 4 – Free Printable' WHERE id = '356';
UPDATE worksheets SET title = 'Simple Machines – Grade 5 Science Worksheet 5 – Free Printable' WHERE id = '357';
UPDATE worksheets SET title = 'States of Matter – Grade 5 Science Worksheet 1 – Free Printable' WHERE id = '338';
UPDATE worksheets SET title = 'States of Matter – Grade 5 Science Worksheet 2 – Free Printable' WHERE id = '339';
UPDATE worksheets SET title = 'States of Matter – Grade 5 Science Worksheet 3 – Free Printable' WHERE id = '340';
UPDATE worksheets SET title = 'States of Matter – Grade 5 Science Worksheet 4 – Free Printable' WHERE id = '341';
UPDATE worksheets SET title = 'States of Matter – Grade 5 Science Worksheet 5 – Free Printable' WHERE id = '342';

-- Also normalize the 70 'Math' → 'math' subject values for consistency
UPDATE worksheets SET subject = 'math' WHERE subject = 'Math';